xl : 10000 # 水路長(m)
nx: 51  # x方向格子数
j_channel: 1 # 水路の状態　1=一定勾配 2=勾配変化点あり
# j_channel=1の場合
slope: 0.001428 # 全体の勾配
# j_channel=2の場合
x_slope : 7 # 勾配変化点
slope1 : 0.014 # 上流側勾配
slope2 : 0.002 # 下流側勾配
xb1 : 1 # 突起始り地点の上流端からの距離（m)
xb2 : 2 # 突起頂点の上流端からの距離(m)
xb3 : 3 # 突起終了地点の上流からの距離(m)
dbed : 0. #突起高さ(m)
xw1 : 1 # 川幅変化点1の位置(m)
xw2 : 2 # 川幅変化点2の位置(m)
xw3 : 3 # 川幅変化点3の位置(m)
w0: 100 # 川幅1(m)(上流端)
w1: 100 # 川幅2(m)
w2: 100 # 川幅3(m)
w3: 100 # 川幅4(m)
w4: 100 # 川幅5(m)(下流端)
qp : 500 #流量(m**3/2)
g : 9.8 #重力加速度
snm : 0.02 # 粗度係数
alh : 0.5 # 水位計算緩和係数
lmax : 20 # 水位計算最大繰り返し回数
errmax : 0.0001 # 打ち切り誤差
hmin : 0.001 # 最小水深(m)
j_upstm : 2 # 上流端の条件 1=Wall, 2=Free, 3=Fixed Value
j_dwstm : 3 # 下流端の条件
j_dwstm_cnd : 2 # 下流端水位の与え方 1=等流水深の倍数, 2=水位を与える
h_downstream : 12.0
j_ini_prof: 3 # 1=上下流以外等流, 2=直線補完, 3=堰上げ水平＋等流水深
alpha_up: 1.0 # 上流端の水深(等流水深に対する割合)
alpha_dw: 1.0 # 下流端の水深(等流水深に対する割合)

etime : 86400 # 計算終了時間(sec)
dt : 0.01 # 計算タイムステップ
tuk : 1200 # アウトプットインターバル
b_start : 600 # 河床変動計算の開始時間(sec)

diam: 0.0001 # 河床材料の粒径(m)
lam: 0.4 # 空隙率
sub: 1.65 # 河床材料の水中比重
nu: 0.000001 # 水の動粘性係数
kappa : 0.4 # カルマン定数

alpha_up_sed: 1.0 #上流端の流砂（平衡流砂量に対する割合)
j_sediment : 2 # 1=掃流砂のみ  2=浮遊砂のみ 3=掃流砂+浮遊砂
j_sus_ini: 2 # 初期濃度 1=濃度0, 2=平衡状態
